pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 1, unit: 'MINUTES: 40')
        disableConcurrentBuilds()
    }
    parameters {
        string(name: 'PERSON', defaultvalue: 'Mr Jenkins', description: 'Who should I say hello to? ')
        text(name: 'BIOGRAPHY', defaultValue: '', description: 'Enter some information')
        booleanparam(name: 'TOGGLE', defaultValue: true, description: 'Toggle this value')
        choice(name: 'CHOICE', choices: ['one', 'Two', 'Three'], description: 'Enter a password')
    }
    environment{
        DEPLOY_TO = 'production'
        GREETING = 'Good Morning'
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo this is build'
                sh 'env'
            }
        }
        stage('Test') {
            steps{
                sh 'echo this is test'
                sleep '10'
            }
        }
        stage('Deploy'){
            steps {
                sh 'echo this is deploy'
            }
        }
        stage('print params'){
            echo "Hello ${params.PERSON}"
            echo "Biography: ${params.BIOGRAPHY}"
            echo "Toggle: ${params.TOGGLE}"
            echo "Choice: ${params.CHOICE}"
            echo "Password: ${params.PASSWORD}"
        }
    }
}
post {
    always {
        echo 'I will always say Hello again!'
    }
    success {
        echo 'I will run when pipeline is success'
    }
    failure {
        echo 'I will run when pipeline is failed'
    }
}